select country, COUNT(customer_key) as total_customers from gold.dim_customers GROUP BY country ORDER BY total_customers DESC;
select gender, COUNT(customer_key) as total_customers from gold.dim_customers GROUP BY gender ORDER BY total_customers DESC;
select category, COUNT(product_key) as total_products from gold.dim_products GROUP BY category order by total_products DESC;
select category, AVG(cost) as avg_costs from gold.dim_products GROUP BY category order by avg_costs DESC

--Total Revenue generated by each category
select 
p.category,
SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_products p on p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Total Revenue generated by each customer
select c.customer_key,
CONCAT(c.first_name, ' ', c.last_name) as full_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key = f.customer_key
GROUP BY c.customer_key,
CONCAT(c.first_name, ' ', c.last_name)
order by total_revenue DESC

-- Distribution of sold items across countries
select c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key = f.customer_key
GROUP BY c.country
order by total_sold_items DESC